platform :ios, '8.0'

target 'App' do
    # react-native-rxdialog #不需要导入，因为都是js代码

    # React-Native
  	pod 'React', :path => '../node_modules/react-native', :subspecs => [
    	'Core',
    	'CxxBridge', # 如果RN版本 >= 0.45则加入此行
    	'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
        'RCTText',
        'RCTImage',
        'RCTNetwork',
        'RCTSettings',
        'RCTVibration',
        'RCTAnimation',
        'RCTActionSheet',
        'RCTGeolocation',
    	'RCTWebSocket', # 这个模块是用于调试功能的

    	# 在这里继续添加你所需要的RN模块
	    'ART',
        'RCTBlob',
        'RCTCameraRoll',
        'RCTLinkingIOS',
        'RCTGeolocation',
        'RCTPushNotification'
  	]
    
  	# 如果你的RN版本 >= 0.42.0，则加入下面这行
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  	 # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
 	pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
 	pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  	pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
	post_install do |installer|
	    installer.pods_project.build_configurations.each do |config|
	      config.build_settings['SYMROOT'] = '${SRCROOT}/../build'
	    end
  	end
end
